/**
 * Bakes icons/*.jpg|png into src/icons.js as data URIs, keyed by file name.
 * Same reason as embed-shots.mjs: the page may not fetch anything off-site.
 * Run: node tools/embed-icons.mjs
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const DIR = 'icons'
const TYPES = { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png' }
const ext = (f) => f.slice(f.lastIndexOf('.')).toLowerCase()
const files = readdirSync(DIR).filter((f) => TYPES[ext(f)]).sort()
let total = 0
const entries = files.map((f) => {
  const bytes = readFileSync(join(DIR, f))
  total += bytes.length
  return `  ${JSON.stringify(f.replace(/\.[^.]+$/, ''))}: "data:${TYPES[ext(f)]};base64,${bytes.toString('base64')}",`
})
writeFileSync(
  'src/icons.js',
  '// Generated by tools/embed-icons.mjs from icons/. Do not hand-edit.\n' +
    'export const ICONS = {\n' + entries.join('\n') + (entries.length ? '\n' : '') + '}\n',
)
console.log(`${files.length} icon(s), ${(total / 1024).toFixed(0)} KB raw`)
