/**
 * Bakes shots/*.jpeg into src/shots.js as data URIs.
 *
 * A Worker has no filesystem at runtime and the page may not fetch anything
 * off-site, so the screenshots have to travel inside the bundle.
 *
 * Run: node tools/embed-shots.mjs
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const DIR = 'shots'
const TYPES = { '.jpeg': 'image/jpeg', '.jpg': 'image/jpeg', '.png': 'image/png' }

const files = readdirSync(DIR)
  .filter((f) => TYPES[f.slice(f.lastIndexOf('.')).toLowerCase()])
  .sort()

let total = 0
const entries = files.map((f) => {
  const bytes = readFileSync(join(DIR, f))
  total += bytes.length
  const mime = TYPES[f.slice(f.lastIndexOf('.')).toLowerCase()]
  const key = f.replace(/\.[^.]+$/, '')
  return `  ${JSON.stringify(key)}: "data:${mime};base64,${bytes.toString('base64')}",`
})

writeFileSync(
  'src/shots.js',
  '// Generated by tools/embed-shots.mjs from shots/. Do not hand-edit.\n' +
    'export const SHOTS = {\n' +
    entries.join('\n') +
    (entries.length ? '\n' : '') +
    '}\n',
)

console.log(`${files.length} screenshot(s), ${(total / 1024).toFixed(0)} KB raw`)
if (total > 900 * 1024) console.warn('WARNING: getting close to the Worker bundle limit')
for (const f of files) console.log('  ' + f)
